// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW9b5kEJd_vFI97tO1VZIu_8xJZaCW10w',
    appId: '1:586602014687:web:48126e98f872052010c66a',
    messagingSenderId: '586602014687',
    projectId: 'sma-product',
    authDomain: 'sma-product.firebaseapp.com',
    storageBucket: 'sma-product.firebasestorage.app',
    measurementId: 'G-GGY60DV2QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Gu_MIg_CLdY-H18rYxm9--DsdFr0HIg',
    appId: '1:586602014687:android:546705208751813810c66a',
    messagingSenderId: '586602014687',
    projectId: 'sma-product',
    storageBucket: 'sma-product.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhwQqVJTmE4FgPHVbF-ZpF_VT-aS3i-3s',
    appId: '1:586602014687:ios:12dd5140bb0a30ea10c66a',
    messagingSenderId: '586602014687',
    projectId: 'sma-product',
    storageBucket: 'sma-product.firebasestorage.app',
    iosBundleId: 'com.example.smaProduct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhwQqVJTmE4FgPHVbF-ZpF_VT-aS3i-3s',
    appId: '1:586602014687:ios:12dd5140bb0a30ea10c66a',
    messagingSenderId: '586602014687',
    projectId: 'sma-product',
    storageBucket: 'sma-product.firebasestorage.app',
    iosBundleId: 'com.example.smaProduct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW9b5kEJd_vFI97tO1VZIu_8xJZaCW10w',
    appId: '1:586602014687:web:3d51bb07b2edc1c410c66a',
    messagingSenderId: '586602014687',
    projectId: 'sma-product',
    authDomain: 'sma-product.firebaseapp.com',
    storageBucket: 'sma-product.firebasestorage.app',
    measurementId: 'G-KFE4QZX9EP',
  );
}
